-- | Closed deterministic declaration transport values and codecs.
module AI4X.DeclarationProtocol
  ( DeclarationProtocolVersion (..),
    SchemaVersion,
    DecoderVersion,
    ProductVersion,
    SemanticNode,
    SourceNode,
    SourceArtifact,
    GenerationIdentity (..),
    GenerationId,
    generationId,
    generationIdDigest,
    SourceMap,
    sourceMap,
    sourceMapEntries,
    Provenance,
    provenance,
    provenanceEntries,
    GenerationManifest,
    generationManifest,
    generationManifestIdentity,
    generationManifestGenerationId,
    generationManifestSourceMapDigest,
    generationManifestProvenanceDigest,
    AcceptedGenerationEnvelope,
    acceptedGenerationEnvelope,
    acceptedGenerationEnvelopeVersion,
    acceptedGenerationEnvelopeGenerationId,
    acceptedGenerationEnvelopeManifestDigest,
    AcceptedGeneration,
    validateAcceptedGeneration,
    acceptedGenerationEnvelopeValue,
    acceptedGenerationManifest,
    acceptedGenerationSemanticPayload,
    acceptedGenerationSourceMap,
    acceptedGenerationProvenance,
    encodeAcceptedGenerationEnvelope,
    decodeAcceptedGenerationEnvelope,
    encodeGenerationManifest,
    decodeGenerationManifest,
    encodeSourceMap,
    decodeSourceMap,
    encodeProvenance,
    decodeProvenance,
    DocumentKind (..),
    DigestRole (..),
    DeclarationDefect (..),
  )
where

import AI4X.DeclarationProtocol.Internal.Protocol
